safe:       false
auto:       true
server:     false
source:     .
markdown:   rdiscount
pygments:   true

title:      Aaron K. White

#url:        http://aaronkwhite.com
permalink:  /post/:title/

author:
    name:       Aaron K. White
    email:      aaron@aaronkwhite.com
    github:     aaronkwhite
    twitter:    aaronkwhite
    gravatar:   http://www.gravatar.com/avatar/a12d1a571d63957f150117f18d87a69f.png

#comments:
#    provider: disqus
#    disqus:
#        short_name: intheatticuk
